logs:
- type: file
  path: "/var/log/agent.log"
  service: "dd-agent"
  source: "dd-agent"
- type: file
  path: "/var/log/trace-agent.log"
  service: "dd-trace-agent"
  source: "dd-agent"
- type: file
  path: "/var/log/process-agent.log"
  service: "dd-process-agent"
  source: "dd-agent"
- type: file
  path: "/var/log/app.log"
  service: "app"
  source: "app"